const convertLogsToCSV = (logs) => {
  const headers = ["Type", "Format", "Generated By", "Timestamp", "Filters"];
  const rows = logs.map(log => [
    log.type,
    log.format,
    `${log.generatedBy?.name || ""} <${log.generatedBy?.email || ""}>`,
    new Date(log.timestamp).toLocaleString(),
    JSON.stringify(log.filters),
  ]);

  return [headers, ...rows].map(row => row.join(",")).join("\n");
};

export default convertLogsToCSV;